name: Build
on:
  push:
    branches: [ main ] 
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    #- name: Build
    #  run: 
    #    mkdir -p ./html/.github/workflows && cp .github/workflows/sitemap.yml ./html/.github/workflows

    - name: Deploy
      if: ${{ github.event_name == 'push' }}
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./html
        cname: www.ritalighosh.com
        user_name: 'RitaliG'
        user_email: 'ritsg11@gmail.com'
        enable_jekyll: false
        publish_branch: gh-pages
        force_orphan: true

  sitemap:
    name: Sitemap
    needs: build
    runs-on: ubuntu-latest
    steps: 
    
    - name: Checkout to the gh-pages branch
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        ref: gh-pages
                
    - name: Sitemap generation
      id: sitemap
      uses: cicirello/generate-sitemap@v1
      with:
        base-url-path: https://www.ritalighosh.com/
        # path-to-root: ./html
        include-pdf: true
        # exclude-path: >
        #  /simulations

    # - name: Create Pull Request
    #   uses: peter-evans/create-pull-request@v6
    #   with:
    #     title: "Automated sitemap update"
    #     body: > 
    #       Sitemap updated by the [generate-sitemap](https://github.com/cicirello/generate-sitemap) 
    #       GitHub action. Automated pull-request generated by the 
    #       [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action.
    #     branch: sitemap-auto-pull
    #     # base: gh-pages
    #     delete-branch: true
    #     author: RitaliG <ritsg11@gmail.com>
    #     committer: RitaliG <ritsg11@gmail.com>
    
    - name: Commit website sitemap and push all commits to gh-pages
      run: |
        if [[ `git status --porcelain` ]]; then
          echo "Pushing new sitemap.xml!"
          git config --global user.name 'RitaliG'
          git config --global user.email 'ritsg11@gmail.com'
          git add .
          git commit -m "Automated sitemap update by GitHub action."
          git push
        else
          echo "Sitemap unchanged. Nothing to push!"
        fi
